// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShowroomBilling.Infrastructure.Persistence;

#nullable disable

namespace ShowroomBilling.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ShowroomBillingDbContext))]
    [Migration("20260423134914_MasterReadIndexes")]
    partial class MasterReadIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShowroomBilling.Infrastructure.Persistence.Entities.AdminPasscodeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Iterations")
                        .HasColumnType("integer");

                    b.Property<string>("PasscodeHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasscodeSalt")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("ShowroomId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ShowroomId")
                        .IsUnique();

                    b.ToTable("admin_passcodes", "public");
                });

            modelBuilder.Entity("ShowroomBilling.Infrastructure.Persistence.Entities.AdminSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorLabel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("ShowroomId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("ShowroomId", "ExpiresAtUtc");

                    b.ToTable("admin_sessions", "public");
                });

            modelBuilder.Entity("ShowroomBilling.Infrastructure.Persistence.Entities.AuditEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("EventType", "CreatedAtUtc");

                    b.HasIndex("EntityType", "EntityId", "CreatedAtUtc");

                    b.ToTable("audit_events", "public");
                });

            modelBuilder.Entity("ShowroomBilling.Infrastructure.Persistence.Entities.BillEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BillType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("CounterId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CurrentRevisionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EditedAfterPush")
                        .HasColumnType("boolean");

                    b.Property<string>("FiscalYear")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("ShowroomId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("SupersededByBillId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("VoidedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ShowroomId", "CreatedAtUtc");

                    b.HasIndex("ShowroomId", "FiscalYear", "InvoiceNumber")
                        .IsUnique()
                        .HasFilter("\"InvoiceNumber\" IS NOT NULL");

                    b.HasIndex("ShowroomId", "State", "CreatedAtUtc");

                    b.ToTable("bills", "public");
                });

            modelBuilder.Entity("ShowroomBilling.Infrastructure.Persistence.Entities.BillRevisionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("BillDate")
                        .HasColumnType("date");

                    b.Property<Guid>("BillId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("FinalizedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("numeric(18,3)");

                    b.Property<string>("PartyName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("RevisionNo")
                        .HasColumnType("integer");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SupersedesRevisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("TotalsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("BillDate");

                    b.HasIndex("BillId", "CreatedAtUtc");

                    b.HasIndex("BillId", "RevisionNo")
                        .IsUnique();

                    b.ToTable("bill_revisions", "public");
                });

            modelBuilder.Entity("ShowroomBilling.Infrastructure.Persistence.Entities.CloudSettingsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActiveCompanyName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("BankAccount")
                        .HasColumnType("text");

                    b.Property<string>("BankIfsc")
                        .HasColumnType("text");

                    b.Property<string>("BankName")
                        .HasColumnType("text");

                    b.Property<string>("BankUpi")
                        .HasColumnType("text");

                    b.Property<string>("CashLedger")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("CgstLedger")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("CompanyAddress")
                        .HasColumnType("text");

                    b.Property<string>("CompanyCountry")
                        .HasColumnType("text");

                    b.Property<string>("CompanyGstin")
                        .HasColumnType("text");

                    b.Property<string>("CompanyPhone")
                        .HasColumnType("text");

                    b.Property<string>("CompanyState")
                        .HasColumnType("text");

                    b.Property<bool>("CopyDuplicateDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("CopyOriginalDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("CopyTriplicateDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("CreditDebitLedger")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("DiscountLedger")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("InvoicePrefix")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("InvoiceSuffix")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ItemMasterDataJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("KaratMappingDataJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<string>("PrintCompanyName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("PrintFontSize")
                        .HasColumnType("integer");

                    b.Property<string>("PrintLayoutJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("PrintTermsFontSize")
                        .HasColumnType("integer");

                    b.Property<string>("RoundOffLedger")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SalesLedger")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SalesVoucherType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SgstLedger")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TermsAndConditions")
                        .HasColumnType("text");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("cloud_settings", "public");
                });

            modelBuilder.Entity("ShowroomBilling.Infrastructure.Persistence.Entities.DraftEditLeaseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AcquiredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BillId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OwnerActorId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("OwnerCounterName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("ReleasedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("RenewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ShowroomId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BillId")
                        .IsUnique()
                        .HasFilter("\"ReleasedAtUtc\" IS NULL");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("ShowroomId", "BillId");

                    b.ToTable("draft_edit_leases", "public");
                });

            modelBuilder.Entity("ShowroomBilling.Infrastructure.Persistence.Entities.InvoiceNumberReservationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("FiscalYear")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("FormattedNumber")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("ReservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReservedForReference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("ReservedValue")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ShowroomId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("ShowroomId", "FiscalYear", "DocumentType");

                    b.ToTable("invoice_number_reservations", "public");
                });

            modelBuilder.Entity("ShowroomBilling.Infrastructure.Persistence.Entities.InvoiceSequenceEntity", b =>
                {
                    b.Property<Guid>("ShowroomId")
                        .HasColumnType("uuid");

                    b.Property<string>("FiscalYear")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("NextValue")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ShowroomId", "FiscalYear", "DocumentType");

                    b.ToTable("invoice_sequences", "public");
                });

            modelBuilder.Entity("ShowroomBilling.Infrastructure.Persistence.Entities.PrintAssetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssetKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("ByteLength")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("ShowroomId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ShowroomId", "AssetKind");

                    b.ToTable("print_assets", "public");
                });

            modelBuilder.Entity("ShowroomBilling.Infrastructure.Persistence.Entities.TallyCompanySnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ShowroomId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("BatchId", "Name");

                    b.HasIndex("ShowroomId", "Name");

                    b.ToTable("tally_company_snapshots", "public");
                });

            modelBuilder.Entity("ShowroomBilling.Infrastructure.Persistence.Entities.TallyLedgerSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("Gstin")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsRevenue")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Parent")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PrimaryGroup")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ShowroomId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("BatchId", "Name");

                    b.HasIndex("ShowroomId", "Name");

                    b.ToTable("tally_ledger_snapshots", "public");
                });

            modelBuilder.Entity("ShowroomBilling.Infrastructure.Persistence.Entities.TallyMasterSnapshotBatchEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FetchedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ItemCount")
                        .HasColumnType("integer");

                    b.Property<string>("MasterType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ShowroomId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("ShowroomId", "MasterType", "FetchedAtUtc");

                    b.HasIndex("ShowroomId", "MasterType", "Status");

                    b.ToTable("tally_master_snapshot_batches", "public");
                });

            modelBuilder.Entity("ShowroomBilling.Infrastructure.Persistence.Entities.TallyStockItemSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Alias")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("BaseUnit")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("HsnCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Karat")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ShowroomId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("BatchId", "Name");

                    b.HasIndex("ShowroomId", "Name");

                    b.ToTable("tally_stock_item_snapshots", "public");
                });

            modelBuilder.Entity("ShowroomBilling.Infrastructure.Persistence.Entities.TallyVoucherTypeSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeemedPositive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ParentType")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ShowroomId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("BatchId", "Name");

                    b.HasIndex("ShowroomId", "Name");

                    b.ToTable("tally_voucher_type_snapshots", "public");
                });

            modelBuilder.Entity("ShowroomBilling.Infrastructure.Persistence.Entities.BillRevisionEntity", b =>
                {
                    b.HasOne("ShowroomBilling.Infrastructure.Persistence.Entities.BillEntity", "Bill")
                        .WithMany("Revisions")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("ShowroomBilling.Infrastructure.Persistence.Entities.TallyCompanySnapshotEntity", b =>
                {
                    b.HasOne("ShowroomBilling.Infrastructure.Persistence.Entities.TallyMasterSnapshotBatchEntity", "Batch")
                        .WithMany("CompanySnapshots")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("ShowroomBilling.Infrastructure.Persistence.Entities.TallyLedgerSnapshotEntity", b =>
                {
                    b.HasOne("ShowroomBilling.Infrastructure.Persistence.Entities.TallyMasterSnapshotBatchEntity", "Batch")
                        .WithMany("LedgerSnapshots")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("ShowroomBilling.Infrastructure.Persistence.Entities.TallyStockItemSnapshotEntity", b =>
                {
                    b.HasOne("ShowroomBilling.Infrastructure.Persistence.Entities.TallyMasterSnapshotBatchEntity", "Batch")
                        .WithMany("StockItemSnapshots")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("ShowroomBilling.Infrastructure.Persistence.Entities.TallyVoucherTypeSnapshotEntity", b =>
                {
                    b.HasOne("ShowroomBilling.Infrastructure.Persistence.Entities.TallyMasterSnapshotBatchEntity", "Batch")
                        .WithMany("VoucherTypeSnapshots")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("ShowroomBilling.Infrastructure.Persistence.Entities.BillEntity", b =>
                {
                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("ShowroomBilling.Infrastructure.Persistence.Entities.TallyMasterSnapshotBatchEntity", b =>
                {
                    b.Navigation("CompanySnapshots");

                    b.Navigation("LedgerSnapshots");

                    b.Navigation("StockItemSnapshots");

                    b.Navigation("VoucherTypeSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
