<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ShowroomBilling.Contracts\ShowroomBilling.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="QuestPDF" />
  </ItemGroup>
</Project>
